# Generated by Django 5.0.1 on 2024-03-26 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_comment_author_comment_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
