# Generated by Django 5.0.1 on 2024-02-06 12:27

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=225)),
                ('mobile_number', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('photos', models.ImageField(upload_to='user_profile/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
